server {
    listen 8111;
    #listen 8112;
    server_name  localhost;
    default_type text/plain;

    location / {
        set_by_lua_block $traceinfo { return ngx_trace and ngx_trace.traceinfo() or ""; }
        echo 'now is edge $hostname  $server_port';
    }
}

