---
###################### run cmd ########################
- name: run
  script: "{{ nginx_stream_script_path_name }} {{ stream_string }} {{ prefix.split(',')[item|int] }} {{ ports.split(',')[item|int] }}"
  loop: "{{ lookup('ansible.utils.index_of', ips, 'eq', inventory_hostname, wantlist=True) }}"
  register: cmd_output
  changed_when: false
  failed_when: false
  ignore_errors: false
  no_log: false
  tags:
    - nginx_stream

###################### gen log ########################
- name: out
  debug:
    msg: "{{ item.stdout_lines }}"
  loop: "{{ cmd_output.results | default([]) }}"
  when:
    - cmd_output is defined
    - cmd_output.results is defined
    - cmd_output.results | length > 0
    - item.stdout_lines is defined
  tags:
    - nginx_stream
