import { test } from '@playwright/test'

const shot = (page: any, name: string) => page.screenshot({ path: `/tmp/opencode/shots/${name}.png` })

test('09 ssl: rsa root ca + rsa cert test.com + publish', async ({ page }) => {
  test.setTimeout(300000)
  // CA 根证书 tab（空状态）
  await page.goto('http://localhost:12345/ssl')
  await page.waitForTimeout(1500)
  await page.locator('.dt', { hasText: 'CA 根证书' }).click()
  await page.waitForTimeout(1000)
  await shot(page, '09-01-ssl-ca-tab-empty')

  // 创建 CA 根证书：RSA
  await page.locator('button', { hasText: '创建 CA 根证书' }).first().click()
  await page.waitForTimeout(800)
  const caModal = page.locator('.modal-overlay:visible')
  await caModal.locator('.ant-select').nth(0).click()
  await page.waitForTimeout(400)
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option', { hasText: 'RSA' }).first().click()
  await caModal.locator('.ant-select').nth(1).click()
  await page.waitForTimeout(400)
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option', { hasText: '演示集群' }).first().click()
  await caModal.getByPlaceholder('例如：生产环境 CA').fill('演示根证书')
  await page.waitForTimeout(400)
  await shot(page, '09-02-ca-create-dialog')
  await caModal.locator('button', { hasText: '创建 CA' }).click()
  await page.waitForTimeout(3000)
  await shot(page, '09-03-ca-created')

  // 生成服务器证书：RSA + 演示根证书 + test.com
  await page.locator('.dt', { hasText: '全部证书' }).click()
  await page.waitForTimeout(800)
  await page.locator('button', { hasText: '生成证书' }).first().click()
  await page.waitForTimeout(800)
  const genModal = page.locator('.modal-overlay:visible')
  await genModal.locator('.ant-select').nth(0).click()
  await page.waitForTimeout(400)
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option', { hasText: 'RSA' }).first().click()
  await genModal.locator('select.form-input').selectOption({ label: '演示集群' })
  await page.waitForTimeout(1200)
  await genModal.locator('.ant-select').nth(1).click()
  await page.waitForTimeout(500)
  await shot(page, '09-04-generate-ca-select')
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option', { hasText: '演示根证书' }).first().click()
  await genModal.getByPlaceholder('输入证书名称').fill('test.com')
  await genModal.getByPlaceholder('example.com').fill('test.com')
  // 域名 SAN：输入 test.com 回车
  await genModal.getByPlaceholder('输入域名后按 Enter').fill('test.com')
  await genModal.getByPlaceholder('输入域名后按 Enter').press('Enter')
  await page.waitForTimeout(400)
  await shot(page, '09-05-generate-filled')
  await genModal.locator('button', { hasText: '生成并保存' }).click()
  await page.waitForTimeout(6000)
  await shot(page, '09-06-generate-log')
  await genModal.locator('button', { hasText: '关闭' }).click()
  await page.waitForTimeout(1500)
  await shot(page, '09-07-cert-created')

  // 发布 test.com 证书
  await page.locator('.ssl-card', { hasText: 'test.com' }).locator('button', { hasText: '发布' }).first().click()
  await page.waitForTimeout(1000)
  const pubModal = page.locator('.modal-overlay:visible').last()
  await pubModal.locator('.action-link', { hasText: '全选' }).first().click()
  await page.waitForTimeout(500)
  await shot(page, '09-08-cert-publish-nodes')
  await pubModal.locator('button', { hasText: '确认发布' }).click()
  await page.waitForTimeout(12000)
  await shot(page, '09-09-cert-publish-result')
})
