import { test } from '@playwright/test'

const shot = (page: any, name: string) => page.screenshot({ path: `/tmp/opencode/shots/${name}.png` })

// 续跑：CA 已存在（演示根证书），仅生成 test.com 证书并发布
test('09b ssl: generate test.com cert + publish', async ({ page }) => {
  test.setTimeout(300000)
  await page.goto('http://localhost:12345/ssl')
  await page.waitForTimeout(1500)
  await page.locator('button', { hasText: '生成证书' }).first().click()
  await page.waitForTimeout(800)
  const genModal = page.locator('.modal-overlay:visible')
  await genModal.locator('.ant-select').nth(0).click()
  await page.waitForTimeout(500)
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option', { hasText: 'RSA' }).first().click()
  await genModal.locator('select.form-input').selectOption({ label: '演示集群' })
  await page.waitForTimeout(1200)
  await genModal.locator('.ant-select').nth(1).click()
  await page.waitForTimeout(600)
  await shot(page, '09-04-generate-ca-select')
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option', { hasText: '演示根证书' }).first().click()
  await genModal.getByPlaceholder('输入证书名称').fill('test.com')
  await genModal.getByPlaceholder('example.com').fill('test.com')
  await genModal.getByPlaceholder('输入域名后按 Enter').fill('test.com')
  await genModal.getByPlaceholder('输入域名后按 Enter').press('Enter')
  await page.waitForTimeout(400)
  await shot(page, '09-05-generate-filled')
  await genModal.locator('button', { hasText: '生成并保存' }).click()
  await page.waitForTimeout(6000)
  await shot(page, '09-06-generate-log')
  await genModal.locator('button', { hasText: '关闭' }).click()
  await page.waitForTimeout(1500)
  await shot(page, '09-07-cert-created')

  // 发布
  await page.locator('.ssl-card', { hasText: 'test.com' }).locator('button', { hasText: '发布' }).first().click()
  await page.waitForTimeout(1000)
  const pubModal = page.locator('.modal-overlay:visible').last()
  await pubModal.locator('.action-link', { hasText: '全选' }).first().click()
  await page.waitForTimeout(500)
  await shot(page, '09-08-cert-publish-nodes')
  await pubModal.locator('button', { hasText: '确认发布' }).click()
  await page.waitForTimeout(12000)
  await shot(page, '09-09-cert-publish-result')
})
