---
######################拷贝slave文件########################
# - name: 打包目录文件
#   shell: "tar -zcvf {{ local_paths }}/{{ file_name }}.tar.gz -C{{ work_paths }}/ {{ dir_name }}"
#   tags:
#     - edge_slave_copy

# - name: 拷贝压缩文件从slave到Master
#   ansible.builtin.fetch:
#     src: "{{ local_paths }}/{{ file_name }}.tar.gz"
# #    dest: "{{ destpath }}/backup-{{ inventory_hostname }}"
#     dest: "{{ destpath }}"
#   tags:
#     - edge_slave_copy

# - name: 解压压缩文件
#   ansible.builtin.unarchive:
#     src: "{{ destpath }}/{{ file_name }}.tar.gz"
#     dest: "{{ destpath }}"  # 替换成ansible-runner主机上的目标目录
#     remote_src: yes
#   tags:
#     - edge_slave_copy

#- name: 将解压后的目录复制到其他主机
#  ansible.builtin.copy:
#    src: "{{ destpath }}/{{ dir_name }}  # 替换成解压后的目录在ansible-runner主机上的路径
#    dest: {{ work_paths }}  # 替换成其他主机上的目标目录
#    remote_src: yes
#    recursive: yes
#  delegate_to: {{ destips }}
#  tags:
#    - edge_slave_copy


# - name: Copy directory
#   copy:
#     src: "{{ srcpath }}"
#     dest:  "{{ destpath }}"
#   delegate_to: "{{ destip }}"
#   run_once: true
#   tags:
#     - edge_slave_copy_to_slave

# - name: Fetch file
#   fetch:
#     src: "{{ srcpath }}"
#     dest: "{{ destpath }}"
#   delegate_to: "{{ srcip }}"
#   run_once: true
#   tags:
#     - edge_slave_copy_to_master