- name: ######### 检测edge server 是否运行 #########
  shell: "ps -ef|grep ./nginx|grep -v grep"
  register: edge_status
  changed_when: false
  failed_when: false
  no_log: true
  tags:
    - edge_status

- name:  检查  nginx.pid 文件
  shell: "cat {{ item.1 }}"
  register: nginx_pid
  when: inventory_hostname == item.0
  with_together:
    - "{{ ips.split(',') }}"
    - "{{ paths.split(',') }}"
  failed_when: nginx_pid.rc != 0 and "No such file or directory" not in nginx_pid.stderr
  ignore_errors: yes
  no_log: true
  tags:
    - edge_status

- name: 输出PID 
  set_fact:
    pid_info: "The contents of nginx.pid are {{ nginx_pid.results | map(attribute='stdout') | select('defined') | first | default('PID不存在') }}"
  loop: "{{ nginx_pid.results }}"
  loop_control:
    loop_var: item
    extended: yes
  tags:
    - edge_status

- name: 显示PID信息
  debug:
    var: pid_info
  tags:
    - edge_status

- name: 判断进程状态
  debug:
    msg: "edge process is {{ 'running' if edge_status.stdout else 'not running' }}"
  when: edge_status.stdout is defined
  tags:
    - edge_status
