###################### cpu,mem,disk log ########################
- name: cpu
  shell: "top -b -n 1 | grep -i 'Cpu(s)' "
  register: cpu_log
  when: inventory_hostname == item.0
  with_together:
    - "{{ ips.split(',') }}"
  failed_when: false
  tags:
    - edge_statistic

- name: memory
  shell: "free -m"
  register: memory_log
  when: inventory_hostname == item.0
  with_together:
    - "{{ ips.split(',') }}"
  failed_when: false
  tags:
    - edge_statistic

- name: disk
  shell: "df -h"
  register: disk_log
  when: inventory_hostname == item.0
  with_together:
    - "{{ ips.split(',') }}"
  failed_when: false
  tags:
    - edge_statistic        

###################### gen log ########################
- name: cpu-gen
  set_fact:
    cpu_log_messages: "{{ cpu_log_messages | default([]) + [item.stdout_lines] }}"
  loop: "{{ cpu_log.results | default([]) }}"
  when:
    - cpu_log is defined
    - cpu_log.results is defined
    - cpu_log.results | length > 0
    - item.stdout_lines is defined
  tags:
    - edge_statistic

- name: memory-gen
  set_fact:
    memory_log_messages: "{{ memory_log_messages | default([]) + [item.stdout_lines] }}"
  loop: "{{ memory_log.results | default([]) }}"
  when:
    - memory_log is defined
    - memory_log.results is defined
    - memory_log.results | length > 0
    - item.stdout_lines is defined
  tags:
    - edge_statistic

- name: disk-gen
  set_fact:
    disk_log_messages: "{{ disk_log_messages | default([]) + [item.stdout_lines] }}"
  loop: "{{ disk_log.results | default([]) }}"
  when:
    - disk_log is defined
    - disk_log.results is defined
    - disk_log.results | length > 0
    - item.stdout_lines is defined
  tags:
    - edge_statistic   

- name: all-gen
  set_fact:
    log_messages: "{{ log_messages | default([]) + cpu_log_messages + memory_log_messages + disk_log_messages  }}"
  tags:
    - edge_statistic       
###################### show log ########################
- name: out
  debug:
    msg: "{{ log_messages }}"
  tags:
    - edge_statistic
